# Используем базовый образ .NET для выполнения приложения
FROM bitnami/dotnet AS base
WORKDIR /app
EXPOSE 80

# Этап сборки образа
FROM bitnami/dotnet AS build
WORKDIR /src
COPY ["WebBackend.csproj", "./"]  # Замените на имя вашего .csproj файла, если оно другое
RUN dotnet restore "./WebBackend.csproj"  # Восстановление зависимостей
COPY . .
WORKDIR "/src/."
RUN dotnet build "WebBackend.csproj" -c Release -o /app/build

# Этап публикации
FROM build AS publish
RUN dotnet publish "WebBackend.csproj" -c Release -o /app/publish

# Финальный образ
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "WebBackend.dll"]  # Замените на имя вашего .dll файла, если оно другое
