version: '3.8'

services:
  frontend:
    image: my-dotnet-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - my-network

networks:
  my-network:
